name: Build binaries

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linux-build:
    name: Build binaries for ${{ matrix.platform.name }}-${{ matrix.arch }}
    runs-on: ${{ matrix.platform.runner }}
    container:
      image: leszko/cuda:11.7.1-cudnn8-devel-ubuntu20.04-all
      env:
        DEBIAN_FRONTEND: noninteractive
    strategy:
      fail-fast: false
      matrix:
        arch:
          - arm64
          - amd64
        platform:
          - name: linux
            runner: ubuntu-latest-m
          - name: windows
            runner: ubuntu-latest-m
        exclude:
          - platform:
              name: windows
            arch: arm64

    steps:
      - name: Setup ubuntu container
        run: |
          apt update
          apt install -yqq build-essential make software-properties-common
          add-apt-repository -y ppa:git-core/ppa
          apt update && apt install -yqq git zip unzip zlib1g-dev zlib1g yasm

      - name: Check out code
        uses: actions/checkout@v4.0.0
        with:
          fetch-depth: 0
          # Check https://github.com/livepeer/go-livepeer/pull/1891
          # for ref value discussion
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up go
        id: go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.4
          cache: true
          cache-dependency-path: go.sum

      - name: Cache ffmpeg
        id: cache-ffmpeg
        uses: actions/cache@v3
        with:
          path: /home/runner/compiled
          key: ${{ runner.os }}-${{ matrix.platform.name }}-${{ matrix.arch }}-ffmpeg-${{ hashFiles('**/install_ffmpeg.sh') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.platform.name }}-${{ matrix.arch }}-ffmpeg-

      - name: Set build environment
        run: |
          echo "GOARCH=${{ matrix.arch }}" >> $GITHUB_ENV
          echo "GOOS=${{ matrix.platform.name }}" >> $GITHUB_ENV
          echo "GO_BUILD_DIR=lp-builds/" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/root/compiled/lib/pkgconfig" >> $GITHUB_ENV
          echo "CPATH=/usr/local/cuda_${{ matrix.arch }}/include" >> $GITHUB_ENV
          echo "LIBRARY_PATH=/usr/local/cuda_${{ matrix.arch }}/lib64" >> $GITHUB_ENV
          echo "CGO_LDFLAGS=-L/usr/local/cuda_${TARGETARCH}/lib64" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          apt update \
            && apt install -yqq software-properties-common curl apt-transport-https lsb-release \
            && curl -fsSl https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - \
            && add-apt-repository "deb https://apt.llvm.org/$(lsb_release -cs)/ llvm-toolchain-$(lsb_release -cs)-12 main" \
            && apt update \
            && apt -yqq install \
              clang-12 clang-tools-12 lld-12 build-essential pkg-config autoconf git python \
              gcc-multilib gcc-mingw-w64 libgcc-9-dev-arm64-cross mingw-w64-tools gcc-mingw-w64-x86-64

          update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-12 30 \
            && update-alternatives --install /usr/bin/clang clang /usr/bin/clang-12 30 \
            && update-alternatives --install /usr/bin/ld ld /usr/bin/lld-12 30

      - name: Install go modules
        if: steps.go.outputs.cache-hit != 'true'
        run: go mod download

      - name: Install ffmpeg
        if: steps.cache-ffmpeg.outputs.cache-hit != 'true'
        run: ./install_ffmpeg.sh

      - name: Build binaries
        env:
          GHA_REF: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }}
        run: |
          git config --global --add safe.directory '*'
          ./ci_env.sh make

      - name: Upload build
        if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
        env:
          GHA_REF: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }}
          GCLOUD_KEY: ${{ secrets.GCLOUD_KEY }}
          GCLOUD_SECRET: ${{ secrets.GCLOUD_SECRET }}
          DISCORD_URL: ${{ secrets.DISCORD_URL }}
        run: ./upload_build.sh

      - name: Upload artifacts for cutting release
        uses: actions/upload-artifact@master
        with:
          name: release-artifacts
          path: releases/

      - name: Notify new build upload
        run: curl -X POST https://holy-bread-207a.livepeer.workers.dev

  macos-build:
    name: Build binaries for ${{ matrix.platform.name }}-${{ matrix.arch }}
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      fail-fast: false
      matrix:
        arch:
          - arm64
          - amd64
        platform:
          - name: darwin
            runner: macos-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4.0.0
        with:
          fetch-depth: 0
          # Check https://github.com/livepeer/go-livepeer/pull/1891
          # for ref value discussion
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up go
        id: go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.4
          cache: true
          cache-dependency-path: go.sum

      - name: Set build environment
        run: |
          echo "GOARCH=${{ matrix.arch }}" >> $GITHUB_ENV
          echo "GOOS=${{ matrix.platform.name }}" >> $GITHUB_ENV
          echo "GO_BUILD_DIR=lp-builds/" >> $GITHUB_ENV

      - name: Cache ffmpeg
        id: cache-ffmpeg
        uses: actions/cache@v3
        with:
          path: ~/compiled
          key: ${{ runner.os }}-${{ matrix.platform.name }}-${{ matrix.arch }}-ffmpeg-${{ hashFiles('**/install_ffmpeg.sh') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.platform.name }}-${{ matrix.arch }}-ffmpeg-

      - name: Install dependencies
        run: brew install coreutils pkg-config

      - name: Install go modules
        # if: steps.go.outputs.cache-hit != 'true'
        run: go mod download

      - name: Install ffmpeg
        if: steps.cache-ffmpeg.outputs.cache-hit != 'true'
        run: ./install_ffmpeg.sh

      - name: Build binaries
        env:
          GHA_REF: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }}
        run: |
          git config --global --add safe.directory '*'
          export PKG_CONFIG_PATH=~/compiled/lib/pkgconfig
          ./ci_env.sh make

      - uses: actions-ecosystem/action-regex-match@v2
        id: match-tag
        with:
          text: ${{ github.ref_name }}
          regex: '^(master|main|v[0-9]+\.\d+\.\d+)$'

      - name: Codesign and notarize binaries
        if: steps.match-tag.outputs.match != '' && matrix.platform.name == 'darwin'
        uses: livepeer/action-gh-codesign-apple@latest
        with:
          developer-certificate-id: ${{ secrets.CI_MACOS_CERTIFICATE_ID }}
          developer-certificate-base64: ${{ secrets.CI_MACOS_CERTIFICATE_BASE64 }}
          developer-certificate-password: ${{ secrets.CI_MACOS_CERTIFICATE_PASSWORD }}
          app-notarization-email: ${{ secrets.CI_MACOS_NOTARIZATION_USER }}
          app-notarization-password: ${{ secrets.CI_MACOS_NOTARIZATION_PASSWORD }}
          app-notarization-team-id: ${{ secrets.CI_MACOS_NOTARIZATION_TEAM_ID }}
          binary-path: "lp-builds/"

      - name: Upload build
        if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
        env:
          GHA_REF: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }}
          GCLOUD_KEY: ${{ secrets.GCLOUD_KEY }}
          GCLOUD_SECRET: ${{ secrets.GCLOUD_SECRET }}
          DISCORD_URL: ${{ secrets.DISCORD_URL }}
        run: ./upload_build.sh

      - name: Upload artifacts for cutting release
        uses: actions/upload-artifact@master
        with:
          name: release-artifacts
          path: releases/

      - name: Notify new build upload
        run: curl -X POST https://holy-bread-207a.livepeer.workers.dev
