name: Build binaries

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linux-build:
    name: Build binaries for ${{ matrix.platform.name }}-${{ matrix.arch }}
    runs-on: ${{ matrix.platform.runner }}
    container:
      image: leszko/go-livepeer-builder:${{ matrix.arch }}
      env:
        DEBIAN_FRONTEND: noninteractive
    strategy:
      fail-fast: false
      matrix:
        arch:
          - arm64
          - amd64
        platform:
          - name: linux
            runner: ubuntu-20.04
          - name: windows
            runner: ubuntu-20.04
        exclude:
          - platform:
              name: windows
            arch: arm64

    steps:
      - name: Check out code
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
          # Check https://github.com/livepeer/go-livepeer/pull/1891
          # for ref value discussion
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up go
        id: go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.4
          cache: true
          cache-dependency-path: go.sum

      - name: Set build environment
        run: |
          echo "GOARCH=${{ matrix.arch }}" >> $GITHUB_ENV
          echo "GOOS=${{ matrix.platform.name }}" >> $GITHUB_ENV
          echo "GO_BUILD_DIR=lp-builds/" >> $GITHUB_ENV

      - name: Build binaries
        env:
          GHA_REF: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }}
        run: |
          git config --global --add safe.directory '*'
          export PKG_CONFIG_PATH="/github/home/compiled/lib/pkgconfig:/root/compiled/lib/pkgconfig:${PKG_CONFIG_PATH}"
          export CPATH="/usr/local/cuda/include"
          export LIBRARY_PATH="/usr/local/cuda/lib64"
          export CGO_LDFLAGS="-L/usr/local/cuda/lib64"
          ./ci_env.sh make

      - name: Upload build
        if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
        env:
          GHA_REF: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }}
          GCLOUD_KEY: ${{ secrets.GCLOUD_KEY }}
          GCLOUD_SECRET: ${{ secrets.GCLOUD_SECRET }}
          DISCORD_URL: ${{ secrets.DISCORD_URL }}
        run: ./upload_build.sh

      - name: Upload artifacts for cutting release
        uses: actions/upload-artifact@master
        with:
          name: release-artifacts
          path: releases/

      - name: Notify new build upload
        run: curl -X POST https://holy-bread-207a.livepeer.workers.dev
